/**
 * Ticket QR Code Display - CampusPulse
 * Shows the QR code for a specific ticket/registration
 */

import React, { useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  Pressable,
  Dimensions,
  Share,
  Platform,
} from 'react-native';
import { useRouter, useLocalSearchParams, Stack } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import Animated, {
  FadeIn,
  FadeInDown,
  FadeInUp,
  useAnimatedStyle,
  useSharedValue,
  withRepeat,
  withSequence,
  withTiming,
} from 'react-native-reanimated';
import { LinearGradient } from 'expo-linear-gradient';

import { tokens } from '@/lib/styles/unified';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const QR_SIZE = SCREEN_WIDTH * 0.65;

// Generate mock QR pattern (in production, use react-native-qrcode-svg)
const QRPlaceholder = ({ size, data }: { size: number; data: string }) => {
  const gridSize = 21; // Standard QR code is 21x21 for version 1
  const cellSize = size / gridSize;

  // Generate pseudo-random pattern based on data
  const pattern: boolean[][] = [];
  let seed = data.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);

  for (let i = 0; i < gridSize; i++) {
    pattern[i] = [];
    for (let j = 0; j < gridSize; j++) {
      // Keep finder patterns (corners)
      if (
        (i < 7 && j < 7) || // Top-left
        (i < 7 && j >= gridSize - 7) || // Top-right
        (i >= gridSize - 7 && j < 7) // Bottom-left
      ) {
        // Finder pattern
        const inOuter = i < 7 && j < 7 ? (i === 0 || i === 6 || j === 0 || j === 6) :
                        i < 7 && j >= gridSize - 7 ? (i === 0 || i === 6 || j === gridSize - 7 || j === gridSize - 1) :
                        (i === gridSize - 7 || i === gridSize - 1 || j === 0 || j === 6);
        const inInner = i < 7 && j < 7 ? (i >= 2 && i <= 4 && j >= 2 && j <= 4) :
                        i < 7 && j >= gridSize - 7 ? (i >= 2 && i <= 4 && j >= gridSize - 5 && j <= gridSize - 3) :
                        (i >= gridSize - 5 && i <= gridSize - 3 && j >= 2 && j <= 4);
        pattern[i][j] = inOuter || inInner;
      } else {
        // Random data pattern
        seed = (seed * 9301 + 49297) % 233280;
        pattern[i][j] = seed / 233280 > 0.5;
      }
    }
  }

  return (
    <View style={[styles.qrContainer, { width: size, height: size }]}>
      {pattern.map((row, i) => (
        <View key={i} style={styles.qrRow}>
          {row.map((cell, j) => (
            <View
              key={j}
              style={[
                styles.qrCell,
                { width: cellSize, height: cellSize },
                cell ? styles.qrCellFilled : styles.qrCellEmpty,
              ]}
            />
          ))}
        </View>
      ))}
    </View>
  );
};

export default function TicketQRScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const params = useLocalSearchParams();

  const {
    ticketNumber = 'CP-2025-0001',
    eventTitle = 'CodeVerse Hackathon 2025',
    date = 'Jan 25, 2025',
    time = '9:00 AM',
    location = 'Innovation Hub',
    status = 'active',
  } = params as Record<string, string>;

  // Animation for the glow effect
  const glowOpacity = useSharedValue(0.5);

  useEffect(() => {
    glowOpacity.value = withRepeat(
      withSequence(
        withTiming(1, { duration: 1500 }),
        withTiming(0.5, { duration: 1500 })
      ),
      -1
    );
  }, []);

  const glowStyle = useAnimatedStyle(() => ({
    opacity: glowOpacity.value,
  }));

  const handleShare = async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    try {
      await Share.share({
        message: `My ticket for ${eventTitle}\n\nTicket #: ${ticketNumber}\nDate: ${date}\nTime: ${time}\nLocation: ${location}\n\nGenerated by CampusPulse`,
        title: 'My Event Ticket',
      });
    } catch (error) {
      console.log('Share error:', error);
    }
  };

  const handleClose = () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    router.back();
  };

  const isActive = status === 'active' || status === 'upcoming';

  return (
    <View style={styles.container}>
      <Stack.Screen options={{ headerShown: false }} />

      {/* Background Gradient */}
      <LinearGradient
        colors={[tokens.colors.primary, '#1a1a2e', '#000000']}
        style={StyleSheet.absoluteFill}
      />

      {/* Header */}
      <Animated.View
        entering={FadeInDown.duration(400)}
        style={[styles.header, { paddingTop: insets.top + 16 }]}
      >
        <Pressable style={styles.closeButton} onPress={handleClose}>
          <Feather name="x" size={24} color="#FFFFFF" />
        </Pressable>
        <Text style={styles.headerTitle}>Event Pass</Text>
        <Pressable style={styles.shareButton} onPress={handleShare}>
          <Feather name="share" size={20} color="#FFFFFF" />
        </Pressable>
      </Animated.View>

      {/* Main Content */}
      <View style={styles.content}>
        {/* QR Code Card */}
        <Animated.View
          entering={FadeIn.delay(200).duration(500)}
          style={styles.qrCard}
        >
          {/* Animated Glow */}
          <Animated.View style={[styles.qrGlow, glowStyle]} />

          {/* QR Code */}
          <View style={styles.qrWrapper}>
            <QRPlaceholder size={QR_SIZE} data={ticketNumber} />
          </View>

          {/* Ticket Number */}
          <View style={styles.ticketNumberContainer}>
            <Text style={styles.ticketLabel}>Ticket Number</Text>
            <Text style={styles.ticketNumber}>{ticketNumber}</Text>
          </View>

          {/* Status Badge */}
          <View style={[
            styles.statusBadge,
            { backgroundColor: isActive ? tokens.colors.successLight : tokens.colors.background.secondary }
          ]}>
            <View style={[
              styles.statusDot,
              { backgroundColor: isActive ? tokens.colors.success : tokens.colors.text.tertiary }
            ]} />
            <Text style={[
              styles.statusText,
              { color: isActive ? tokens.colors.success : tokens.colors.text.tertiary }
            ]}>
              {status === 'active' ? 'Active' : status === 'upcoming' ? 'Upcoming' : 'Used'}
            </Text>
          </View>
        </Animated.View>

        {/* Event Details */}
        <Animated.View
          entering={FadeInUp.delay(400).duration(400)}
          style={styles.eventDetails}
        >
          <Text style={styles.eventTitle}>{eventTitle}</Text>

          <View style={styles.detailsRow}>
            <View style={styles.detailItem}>
              <Feather name="calendar" size={16} color="rgba(255,255,255,0.6)" />
              <Text style={styles.detailText}>{date}</Text>
            </View>
            <View style={styles.detailItem}>
              <Feather name="clock" size={16} color="rgba(255,255,255,0.6)" />
              <Text style={styles.detailText}>{time}</Text>
            </View>
          </View>

          <View style={styles.detailItem}>
            <Feather name="map-pin" size={16} color="rgba(255,255,255,0.6)" />
            <Text style={styles.detailText}>{location}</Text>
          </View>
        </Animated.View>

        {/* Instructions */}
        <Animated.View
          entering={FadeInUp.delay(600).duration(400)}
          style={styles.instructions}
        >
          <Feather name="info" size={16} color="rgba(255,255,255,0.4)" />
          <Text style={styles.instructionsText}>
            Show this QR code at the venue for check-in. Keep your screen brightness high for easy scanning.
          </Text>
        </Animated.View>
      </View>

      {/* Bottom Actions */}
      <Animated.View
        entering={FadeInUp.delay(800).duration(400)}
        style={[styles.bottomSection, { paddingBottom: insets.bottom + 20 }]}
      >
        <Pressable style={styles.addToWalletButton}>
          <Feather name="credit-card" size={20} color={tokens.colors.primary} />
          <Text style={styles.addToWalletText}>Add to Wallet</Text>
        </Pressable>
      </Animated.View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  shareButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  qrCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 24,
    alignItems: 'center',
    width: '100%',
    maxWidth: 340,
    position: 'relative',
    overflow: 'hidden',
  },
  qrGlow: {
    position: 'absolute',
    top: -50,
    left: -50,
    right: -50,
    bottom: -50,
    backgroundColor: tokens.colors.primary,
    opacity: 0.1,
  },
  qrWrapper: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 16,
    marginBottom: 20,
  },
  qrContainer: {
    backgroundColor: '#FFFFFF',
  },
  qrRow: {
    flexDirection: 'row',
  },
  qrCell: {
    // Size set dynamically
  },
  qrCellFilled: {
    backgroundColor: '#000000',
  },
  qrCellEmpty: {
    backgroundColor: '#FFFFFF',
  },
  ticketNumberContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  ticketLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: tokens.colors.text.tertiary,
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  ticketNumber: {
    fontSize: 20,
    fontWeight: '700',
    color: tokens.colors.text.primary,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusText: {
    fontSize: 14,
    fontWeight: '600',
  },
  eventDetails: {
    alignItems: 'center',
    marginTop: 32,
    paddingHorizontal: 20,
  },
  eventTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 16,
  },
  detailsRow: {
    flexDirection: 'row',
    gap: 24,
    marginBottom: 12,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailText: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.8)',
  },
  instructions: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginTop: 40,
    paddingHorizontal: 20,
  },
  instructionsText: {
    flex: 1,
    fontSize: 13,
    color: 'rgba(255,255,255,0.4)',
    lineHeight: 18,
  },
  bottomSection: {
    paddingHorizontal: 20,
  },
  addToWalletButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    borderRadius: 16,
  },
  addToWalletText: {
    fontSize: 16,
    fontWeight: '700',
    color: tokens.colors.primary,
  },
});
